### ISSUE TITLE
I got an error.

### ISSUE THREAD

**Issue by RedheatWei** [confirm/django-fulltext-search#6]
My Django version is 2.0.5 and python is 3.6, I got an error like this.
`Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/data/opsplatform/public/views.py", line 16, in inner
    return func(reqeust, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/opsplatform/cmdb/views.py", line 50, in get
    AssetSInfo.objects.search('12312')
  File "/usr/local/lib/python3.6/site-packages/django_fulltext_search-0.2.0-py3.6.egg/django_fulltext_search.py", line 155, in search
    return self.get_query_set().search(query, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_fulltext_search-0.2.0-py3.6.egg/django_fulltext_search.py", line 75, in search
    column = meta.get_field(field, many_to_many=False).column
TypeError: get_field() got an unexpected keyword argument 'many_to_many'`
My python code is this:
`AssetSInfo.objects.search('12312')`

**Comment by Arjune7** [comment]
column = meta.get_field(field, many_to_many=False).column
remove many_to_many=False from here, inside the django_fulltext_search.py file it will workout perfectly!
